DROP TABLE IF EXISTS prestamos;
DROP SEQUENCE IF EXISTS PRESTAMOS_SEQ;

CREATE SEQUENCE PRESTAMOS_SEQ;
ALTER SEQUENCE PRESTAMOS_SEQ INCREMENT by 1;

CREATE TABLE prestamos (ID INTEGER AUTO_INCREMENT PRIMARY KEY ,
                  ISBN VARCHAR(10),
                  IDENTIFICACIONUSUARIO VARCHAR(10),
                  TIPOUSUARIO INTEGER,
                  FECHAMAXIMADEVOLUCION DATE
                   );